language: minimal

addons:
  apt:
    packages:
      - luarocks

install:
  - luarocks install --local luacheck
  - export PATH=${PATH}:~/.luarocks/bin

script:
  - make test
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then ./wowace_translations.sh; fi

notifications:
  email:
    on_failure: always
    on_success: never

